using System.Text.Json.Serialization;
using FastEInvoice.Models.Common;

namespace FastEInvoice.Models.Invoice;

/// <summary>
/// Invoice information from query response
/// </summary>
public class InvoiceInfo
{
    /// <summary>
    /// Original key from request
    /// </summary>
    [JsonPropertyName("key")]
    public string Key { get; set; } = string.Empty;

    /// <summary>
    /// Invoice key generated by portal
    /// </summary>
    [JsonPropertyName("invoiceKey")]
    public string InvoiceKey { get; set; } = string.Empty;

    /// <summary>
    /// Invoice pattern
    /// </summary>
    [JsonPropertyName("pattern")]
    public string Pattern { get; set; } = string.Empty;

    /// <summary>
    /// Invoice serial
    /// </summary>
    [JsonPropertyName("serial")]
    public string Serial { get; set; } = string.Empty;

    /// <summary>
    /// Invoice number
    /// </summary>
    [JsonPropertyName("invoiceNo")]
    public string InvoiceNo { get; set; } = string.Empty;

    /// <summary>
    /// Invoice date (dd/MM/yyyy)
    /// </summary>
    [JsonPropertyName("invoiceDate")]
    public string InvoiceDate { get; set; } = string.Empty;

    /// <summary>
    /// Currency code
    /// </summary>
    [JsonPropertyName("currency")]
    public string? Currency { get; set; }

    /// <summary>
    /// Exchange rate
    /// </summary>
    [JsonPropertyName("exchangeRate")]
    public decimal? ExchangeRate { get; set; }

    /// <summary>
    /// Total amount
    /// </summary>
    [JsonPropertyName("totalAmount")]
    public decimal TotalAmount { get; set; }

    /// <summary>
    /// Invoice lookup code
    /// </summary>
    [JsonPropertyName("keySearch")]
    public string KeySearch { get; set; } = string.Empty;

    /// <summary>
    /// Invoice status
    /// 1 = Waiting for authentication
    /// 2 = Authenticated
    /// 8 = Cancelled
    /// </summary>
    [JsonPropertyName("status")]
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public InvoiceStatus Status { get; set; }

    /// <summary>
    /// Status description
    /// </summary>
    [JsonIgnore]
    public string StatusDescription => Status.GetDescription();

    /// <summary>
    /// Check if invoice is editable
    /// </summary>
    [JsonIgnore]
    public bool IsEditable => Status.IsEditable();
}